### ISSUE TITLE
Flaky test app-luatest/gh_5747_crash_multiple_args_test.lua

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#265] opened 2022-10-05 19:39 UTC
Test [app-luatest/gh_5747_crash_multiple_args_test.lua](https://github.com/tarantool/tarantool/blob/2.10/test/app-luatest/gh_5747_crash_multiple_args_test.lua) is flaky

Branches:

- [ ] master
- [ ] 2.10
- [ ] 1.10

Fails over last 30 days: 194
Arch: x86_64/aarch64
gc64: any

<img width="815" alt="Screenshot 2022-10-06 at 01 38 30" src="https://user-images.githubusercontent.com/8015154/194147710-6efaae6f-75d6-41ac-8f76-e590bad6ef36.png">
<img width="817" alt="Screenshot 2022-10-06 at 01 38 40" src="https://user-images.githubusercontent.com/8015154/194147752-4016c8aa-031f-4782-ad48-8e405ef924a6.png">

**Comment by Gumix** [comment] 2022-11-07 10:09
Here is some investigation: https://github.com/tarantool/tarantool/issues/7886

**Comment by alyapunov** [comment] 2022-11-14 10:23
Closed as duplicate of https://github.com/tarantool/tarantool/issues/7886.

**Closed by alyapunov** 2022-11-14 10:23 UTC
Labels: flaky test, teamC
