### ISSUE TITLE
test: flaky engine-luatest/pagination_test.lua

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#291] opened 2022-12-06 07:09 UTC
Test https://github.com/tarantool/tarantool/blob/master/test/engine-luatest/pagination_test.lua is flaky

* branch: master
* OS and version: all Linux
* Architecture: mostly aarch64
* gc64: mostly on

<img width="819" alt="Screenshot 2022-12-06 at 13 09 32" src="https://user-images.githubusercontent.com/8015154/205844714-0bc4b4f3-3b82-41cf-a58d-71f1a5108c67.png">

**Comment by Buristan** [comment] 2023-12-18 08:53
Duplicate of tarantool/tarantool#7739. 
Fixed via https://github.com/tarantool/tarantool/commit/15e62a67d3e8d60e85b7c7dc6bc80cd9bb23d79d (backported in 2.11 via https://github.com/tarantool/tarantool/commit/a7a02300721413230c7693e39e99a96927015401). JIT for the test is enabled back by the https://github.com/tarantool/tarantool/commit/915e0b3a4475b12ec49320421569524dc8488aed (backported in 2.11 via https://github.com/tarantool/tarantool/commit/dbbeaff982022288faafb773930c75ba938f62f2).

**Closed as completed by Buristan** 2023-12-18 08:53 UTC
Labels: flaky test, arm, luajit
